//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RealPopup.rc
//
#define IDS_DDXFILE_TT_MODIFY           1
#define IDS_DDXFILE_TT_CAPTION          1
#define IDS_DDXFILE_OK                  2
#define IDS_DDXFILE_EDIT_TEXT           3
#define ID_CMD_DEFAULT                  3
#define IDS_DDXFILE_OVERWRITE_PROMPT    4
#define IDS_DDXFILE_REQUIRE_VALID_FILE  5
#define IDS_DDXFILE_FILTER_LOG          5
#define IDR_RPENABLED                   5
#define IDS_DDXFILE_FILTER_WAV          6
#define IDS_DDXFILE_FILTER_TXT          7
#define FMT_LOG_DATE                    8
#define FMT_LOG_FROMTO                  9
#define OPTIONS_CAPTION                 10
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REALPOPUP_DIALOG            102
#define IDD_DLG_MAIN                    102
#define IDR_ACCELERATORI                102
#define IDR_ACCMENU1                    102
#define IDD_PP_ENV                      106
#define IDD_PP_LANG                     107
#define IDR_MAINFRAME                   128
#define IDD_DLG_SENDMESSAGE             134
#define IDR_MENU1                       135
#define IDD_PP_USERS                    135
#define IDR_MENU2                       138
#define IDR_MENU_TRAY                   139
#define IDC_CURSOR_LINK                 141
#define IDR_TRAYICON                    144
#define IDB_BITMAP_LOGO                 147
#define IDR_MSGARRIVED                  149
#define IDR_ACCELERATOR1                150
#define IDR_MSGDISABLED                 150
#define IDD_DLG_NETWORK                 153
#define IDD_PP_MSG                      154
#define IDB_NETTREE                     155
#define IDR_PLAY                        159
#define IDR_NETWORK                     160
#define IDR_WELCOMEMSG                  163
#define IDR_ACCMENU2                    165
#define IDR_EDITFONT                    166
#define IDR_RICHEDITFONT                167
#define IDR_POSSAVE                     168
#define IDR_POSDEFAULT                  169
#define IDB_STANZA                      174
#define IDB_STANZASF                    175
#define IDR_SRCINSERT                   178
#define IDD_CRITERIA                    179
#define IDR_MSGARRIVED2                 181
#define IDR_MSGAWAY                     182
#define IDD_SERVICE                     183
#define IDR_SERVICE                     184
#define IDB_BITMAP_RPLOGO               188
#define IDR_TOOLBAR1                    191
#define IDB_TOOLBAR1HI                  192
#define IDB_TOOLBAR1HIHOT               193
#define IDB_TOOLBAR1HIDIS               194
#define IDR_TOOLBAR2                    195
#define IDB_TOOLBAR2HI                  196
#define IDB_TOOLBAR2HIHOT               197
#define IDB_TOOLBAR2HIDIS               198
#define IDB_BITMAP3                     198
#define IDR_RT_MANIFEST1                200
#define IDR_RT_MANIFEST2                201
#define IDB_BITMAP1                     202
#define IDB_NETTREEHI                   202
#define IDR_WPENABLED                   204
#define IDR_WBDISABLED                  205
#define IDR_WPDISABLED                  205
#define IDI_ICON1                       206
#define IDI_ICON2                       207
#define IDR_RPDISABLED                  207
#define TXT_MSG                         1001
#define TXT_PROTOCOLLO                  1005
#define IDC_BTN_SCAN                    1006
#define TXT_FROM                        1011
#define TXT_MAIN_FROM                   1011
#define TXT_TO                          1012
#define TXT_MAIN_INFO                   1013
#define IDC_RICHEDIT_ABOUT              1014
#define IDC_TO                          1015
#define IDC_MAIN_FROM                   1016
#define IDC_MAIN_TO                     1017
#define TXT_MAIN_TO                     1018
#define TXT_MAIN_MSG                    1021
#define IDC_CHK_TOP                     1022
#define IDC_CHK_BEEP                    1024
#define IDC_BUTTON1                     1025
#define IDC_CHK_MINIMIZE                1025
#define IDC_BTN_ADD                     1025
#define IDC_TXT_USER                    1026
#define IDC_CHK_WARN                    1026
#define IDC_TXT_MEMBERS                 1027
#define IDC_CHK_DELORIGINAL             1027
#define IDC_OPT_USER                    1028
#define IDC_CHK_AUTOSTART               1028
#define IDC_OPT_GROUP                   1029
#define IDC_CHK_WAV                     1029
#define IDC_LIST1                       1030
#define IDC_LISTUSERS                   1030
#define IDC_CHK_BALLOONONMSGFAILS       1030
#define IDC_LSTLANGUAGE                 1030
#define IDC_CHECK1                      1031
#define IDC_CHK_IGNORE                  1031
#define IDC_CHK_QUOTE                   1031
#define IDC_CHECK2                      1032
#define IDC_CHK_POPUPNEW                1032
#define IDC_CHK_DBLCLICK                1032
#define IDC_BUTTON2                     1033
#define IDC_BTN_REMOVE                  1033
#define IDC_PLAY                        1033
#define IDC_LBL_MEMBERS                 1034
#define IDC_CHK_WARNDEL                 1034
#define IDC_CHK_BALLOONNEW              1034
#define IDC_CHK_LASTMSG2                1034
#define IDC_CHK_LASTMSG                 1034
#define IDC_BTN_SAVEWIN                 1035
#define IDC_CHK_USESRP                  1035
#define IDC_CHK_SENDPCNAME              1035
#define IDC_CHK_AWAY2                   1035
#define IDC_CHK_AWAY                    1035
#define IDC_CHK_NBDETERMINEFAVORITES    1036
#define IDC_CHK_REDIRECT                1036
#define IDC_CHK_REPLYTOP                1036
#define IDC_TXT_REDIRECT                1037
#define IDC_CHK_LEFTTRAY                1037
#define IDC_CHK_DISABLEDEL              1037
#define IDC_CHK_LOG                     1038
#define IDC_BTN_SAVEWINDEF              1038
#define IDC_CHK_WARNDOMAIN              1038
#define IDC_CHK_REPLYTOP2               1038
#define IDC_CHK_CRSEND                  1038
#define IDC_TXT_LOG                     1039
#define IDC_CHK_MINIMIZEREPL            1039
#define IDC_BTN_FONTRICHEDIT            1039
#define IDC_CHK_WARNDOMAIN2             1039
#define IDC_CHK_WARNRPPROTOCOLNOTACTIVE 1039
#define IDC_CHK_ONLINEWARN              1040
#define IDC_BTN_FONTEDIT                1040
#define IDC_SPIN_USER                   1041
#define IDC_TXT_WAV                     1042
#define IDC_NETWORK                     1042
#define IDC_TREE1                       1043
#define IDC_NETWORK2                    1043
#define IDC_NETWORK3                    1044
#define IDC_STATICLOGO                  1044
#define IDC_STATICSIG                   1045
#define IDC_SRCINSERT                   1045
#define IDC_TXT_ABOUTVERSION            1045
#define IDC_LANGUAGE                    1046
#define IDC_CHK_BALLOONNEW2             1046
#define IDC_CHK_BALLOONPREVIEW          1046
#define IDC_CRITERIA                    1047
#define IDC_CHK_NBINCLUDEFAVORITES      1047
#define IDC_SEARCHCRITERIA              1049
#define IDC_RPHOTKEY                    1051
#define IDC_RADIO1                      1052
#define IDC_RADIO3                      1053
#define IDC_MSN                         1053
#define IDC_OPT_NBINCLUDEASMEMBERS      1053
#define IDC_RADIO2                      1054
#define IDC_RADIO4                      1055
#define IDC_MSN2                        1055
#define IDC_STATIC_MSN1                 1056
#define IDC_STATIC_MSN2                 1057
#define IDC_CBO_USESRP                  1059
#define CBO_TO                          1063
#define IDC_OPT_NBINCLUDEASGROUP        1065
#define edt1                            0x0480
#define ID_BTN_NEW                      32771
#define ID_BTN_ANSWER                   32772
#define ID_BTN_ANSWERALL                32773
#define ID_BTN_FORWARD                  32774
#define ID_BTN_DELTHREAD                32775
#define ID_BTN_RESUMETHREADS            32776
#define ID_BTN_DELALL                   32777
#define ID_BTN_DEL                      32778
#define ID_BTN_PREV                     32779
#define ID_BTN_NEXT                     32780
#define ID_BTN_COPY                     32781
#define ID_BTN_SAVE                     32782
#define ID_BTN_SEND                     32783
#define ID_BTN_CANCEL                   32784
#define ID_BTN_OPTIONS                  32785
#define ID_BTN_ABOUT                    32786
#define ID_BTN_WELCOMEMSG               32787
#define ID_BTN_HELP                     32788
#define ID_TRAY_OPEN                    32789
#define ID_TRAY_MINIMIZE                32790
#define ID_TRAY_DISABLE                 32791
#define ID_TRAY_EXIT                    32792
#define ID_TRAY_REDIRECT                32793
#define ID_TRAY_AWAY                    32794
#define ID_BTN_NETWORK                  32795
#define ID_MNU_HELP                     32796
#define ID_HELPFILE                     32797
#define ID_BTN_SENDCOPY                 32798
#define ID_BTN_SENDCUT                  32799
#define ID_BTN_SENDPASTE                32800
#define STATUS_WPPROTOCOLENABLED        32810
#define STATUS_RPPROTOCOLENABLED        32811
#define MSG_SEND_ERROR                  57346
#define MSG_POPUP_ERRINIT               57347
#define MSG_DIALOG_CAPTION              57348
#define DEF_USERNAME                    57349
#define AUTOMSG_BETA_FROM               57350
#define AUTOMSG_BETA_TO                 57351
#define AUTOMSG_BETA_MSG                57352
#define MSG_BETA_OUT                    57353
#define MSG_VERSION                     57354
#define MSG_STATUS_WPSENT               57355
#define MSG_STATUS_RPSENT               57356
#define MSG_ABOUT                       57357
#define MSG_WARNONEXIT                  57358
#define MSG_RECEIVE_MULTIPARTERROR      57359
#define MSG_SEND_MULTIPARTERROR         57360
#define MSG_REALPOPUP_ERRINIT           57361
#define MSG_USERS_ERRLOAD               57362
#define DEF_ALLUSERS                    57363
#define TOOLTIP_IDLE                    57364
#define TOOLTIP_MSG                     57365
#define TOOLTIP_MSGS                    57366
#define MSG_ERRNOTRECEIVED              57367
#define MSG_STATUS_NOTRECEIVED          57368
#define MSG_ONLINEWARN                  57369
#define MSG_STATUS_ONLINEWARNNOTRECEIVED 57370
#define MSG_ONLINEWARNSTATUS            57371
#define MSG_REDIRECTING                 57372
#define MSG_REDIRECTING_ERR             57373
#define MSG_LOGHEAD                     57374
#define MSG_STATUS_TOOLONG              57375
#define MSG_ERRTOOLONG                  57376
#define MSG_STATUS_RPSENT_OLDVER        57377
#define AUTOMSG_BETA_MSG2               57378
#define MSG_ERRDISABLED                 57379
#define MSG_WARNONCANCELINGSEND         57380
#define MSG_ERR_NOTCREATABLE            57381
#define MSG_SAVEHEAD                    57382
#define MSG_AUTOSTART_WARN              57383
#define MSG_AUTOSTART_MSG               57384
#define MSG_LOCALIZE_ABOUT              57385
#define MSG_LOCALIZE_DESC               57386
#define IDS_WEEKDAYS                    57387
#define MSG_ERR_USERINSERT              57388
#define MSG_SEARCHCRITERIA              57389
#define MSG_ERR_HOTKEY                  57390
#define MSG_ERR_REPLY                   57391
#define MSG_ERRAWAY                     57392
#define MSG_ERR_MSNSTOPDENIED           57393
#define MSG_ERR_MSNSTOPERR              57394
#define MSG_STATUS_CMDLINESENT          57395
#define MSG_CMDLINE_HELP                57396
#define MSG_NBROWSER_RPUSERS            57397
#define MSG_WARNDOMAIN                  57398
#define ITEM_USESREALPOPUP              57399
#define ITEM_USESWINPOPUP               57400
#define MSG_WELCOME                     57401
#define MSG_INTERNALMSGHEAD             57402
#define MSG_BALLOON_NEWMSG              57403
#define MSG_MESSAGESWAITING             57404
#define MSG_BALLOON_ERRMSG              57405
#define MSG_OFFLINEWARNSTATUS           57406
#define TOOLTIP_STATUS_WPENABLED        57407
#define TOOLTIP_STATUS_RPENABLED        57408
#define TOOLTIP_STATUS_WPDISABLED       57409
#define TOOLTIP_STATUS_RPDISABLED       57410
#define MSG_POPUP_ERRMSGSERVICE         57411
#define MSG_BALLOON_POPUP_ERRMSGSERVICE 57412
#define MSG_BALLOON_POPUP_ERRINIT       57413
#define MSG_BALLOON_REALPOPUP_ERRINIT   57414
#define MSG_ERR_HOTKEYHEAD              57415

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
